{
 "title": "Scheduler",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Build Queuing Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(result) (histogram_quantile(0.5, scheduler_build_queue_latency_bucket))",
     "legendFormat": "50p_{{result}}"
    },
    {
     "expr": "sum by(result) (histogram_quantile(0.9, scheduler_build_queue_latency_bucket))",
     "legendFormat": "90p_{{result}}"
    },
    {
     "expr": "sum by(result) (histogram_quantile(0.99, scheduler_build_queue_latency_bucket))",
     "legendFormat": "99p_{{result}}"
    }
   ]
  },
  {
   "title": "Active Builds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(category) (scheduler_active_builds{category!=\"total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(category) (scheduler_active_workers{category!=\"total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Builds (in-memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "scheduler_active_builds{category=\"total\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Total Workers (in-memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "scheduler_active_workers{category=\"total\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Build Creations",
   "type": "timeseries",
   "description": "Number of builds created (per second",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_rpc_count{service=\"builds\", method=\"create_build\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(result) (rate(scheduler_rpc_count{service=\"builds\", method=\"create_build\", result!=\"ok\"}[$__rate_interval]))",
     "legendFormat": "error_{{result}}"
    }
   ]
  },
  {
   "title": "Build Completions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_builds_completed_count[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(result) (rate(scheduler_builds_completed_count{result!~\"ok\"}[$__rate_interval]))",
     "legendFormat": "error_{{result}}"
    }
   ]
  },
  {
   "title": "Worker Registrations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_rpc_count{service=\"workers\", method=\"register_worker\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(result) (rate(scheduler_rpc_count{service=\"workers\", method=\"register_worker\", result!=\"ok\"}[$__rate_interval]))",
     "legendFormat": "error_{{result}}"
    }
   ]
  },
  {
   "title": "Worker Heartbeats",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_rpc_count{service=\"workers\", method=\"build_heart_beat\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(result) (rate(scheduler_rpc_count{service=\"workers\", method=\"build_heart_beat\", result!=\"ok\"}[$__rate_interval]))",
     "legendFormat": "error_{{result}}"
    }
   ]
  },
  {
   "title": "Worker Accept Build",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_rpc_count{service=\"workers\", method=\"accept_build\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(result) (rate(scheduler_rpc_count{service=\"workers\", method=\"accept_build\", result!=\"ok\"}[$__rate_interval]))",
     "legendFormat": "error_{{result}}"
    }
   ]
  },
  {
   "title": "Lock Acquisition Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum by(lock) (histogram_quantile(0.5, scheduler_lock_wait_latency_bucket))",
     "legendFormat": "50p_{{lock}}"
    },
    {
     "expr": "sum by(lock) (histogram_quantile(0.9, scheduler_lock_wait_latency_bucket))",
     "legendFormat": "90p_{{lock}}"
    },
    {
     "expr": "sum by(lock) (histogram_quantile(0.99, scheduler_lock_wait_latency_bucket))",
     "legendFormat": "99p_{{lock}}"
    }
   ]
  },
  {
   "title": "Lock Waiters",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "sum by(lock) (scheduler_lock_waiters)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collection Cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "rate(scheduler_gc_cycles[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collection Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.5, scheduler_gc_latency_bucket))",
     "legendFormat": "50p"
    },
    {
     "expr": "sum(histogram_quantile(0.9, scheduler_gc_latency_bucket))",
     "legendFormat": "90p"
    },
    {
     "expr": "sum(histogram_quantile(0.99, scheduler_gc_latency_bucket))",
     "legendFormat": "99p"
    }
   ]
  }
 ]
}